export default {
  login: 'padmajabhol',
  id: 75530516,
  node_id: 'MDQ6VXNlcjc1NTMwNTE2',
  avatar_url: 'https://avatars.githubusercontent.com/u/75530516?v=4',
  gravatar_id: '',
  url: 'https://api.github.com/users/padmajabhol',
  html_url: 'https://github.com/padmajabhol',
  followers_url: 'https://api.github.com/users/padmajabhol/followers',
  following_url: 'https://api.github.com/users/padmajabhol/following{/other_user}',
  gists_url: 'https://api.github.com/users/padmajabhol/gists{/gist_id}',
  starred_url: 'https://api.github.com/users/padmajabhol/starred{/owner}{/repo}',
  subscriptions_url: 'https://api.github.com/users/padmajabhol/subscriptions',
  organizations_url: 'https://api.github.com/users/padmajabhol/orgs',
  repos_url: 'https://api.github.com/users/padmajabhol/repos',
  events_url: 'https://api.github.com/users/padmajabhol/events{/privacy}',
  received_events_url: 'https://api.github.com/users/padmajabhol/received_events',
  type: 'User',
  site_admin: false,
  name: 'Padmaja Bhol',
  company: 'National Institute of Technology, Rourkela',
  blog: 'padmajabhol.tech',
  location: 'Bhubaneswar',
  email: null,
  hireable: null,
  bio: 'Hemlo!',
  twitter_username: 'padmajab24',
  public_repos: 57,
  public_gists: 0,
  followers: 32,
  following: 28,
  created_at: '2020-12-05T13:08:48Z',
  updated_at: '2022-01-28T06:03:26Z',
};
